### ISSUE TITLE
Missing field titles causes warning in studio development mode.

### ISSUE THREAD

**Issue by mattjoc-braze** [davydog187/sanity-portable-table#6]
Hi there! It looks like the `table-cell-body`, `table-cell`, and `table-row` fields don't specify a title. This causes the studio to throw a warning when in development mode.
<img width="983" alt="Screen Shot 2023-03-21 at 11 06 51 AM" src="https://user-images.githubusercontent.com/77362385/226649381-26f0a520-83bc-4933-b159-31df624429ff.png">

**Comment by davydog187** [comment]
thanks for the report @mattjoc-braze! Would you be interested in submitting a PR to fix?

**Comment by mattjoc-braze** [comment]
Sure thing, @davydog187! I have a working branch locally, so if you want to give me permissions, I can push that branch and make a PR.

**Comment by sebastiangraz** [comment]
Can confirm I have the same issue, @mattjoc-braze mind sharing the branch if you dont get to do a PR?

**Comment by davydog187** [comment]
@mattjoc-braze please fork the project, and then you can submit a PR from that fork

**Comment by mattjoc-braze** [comment]
Done!
